### ISSUE TITLE
Incognito browsing should prevent SW launch

### ISSUE THREAD

**Issue by Ethiarpus** [WICG/sw-launch#28]
If a user is browsing in an "incognito mode" or equivalent (possibly in order not to have items added to their search or history), links they click should not open in SWs (adding items to their history and potentially exposing browsing data to the company) For example, if a user in incognito mode clicks an article set to open with a news site's PWA, suddenly that particular article is associated with a (possibly authenticated) non-incognito session.  
Disabling PWA app handling in incognito should be the default, as is the standard with opening non-SW native apps from links. For example, opening a YouTube link in Chrome opens the YouTube app on iOS and Android, whereas an Incognito or InPrivate browsing session will ignore the handler and use the website instead. This functionality should be replicated with SW link handlers.

**Comment by alancutter** [comment]
This concerns link capturing rather than launch_handler. launch_handler deals with how to handle app launches while link capturing is a source of app launches. Link capturing as a behaviour is more at the browser's discretion to do than something defined in spec.
For what it's worth Chromium's link capturing does not get triggered in incognito windows.
